### ISSUE TITLE
2.0.0 Roadmap

### ISSUE THREAD

**Issue by sisoe24** [sisoe24/nukeserversocket#35]
## Brainstorming Ideas (Work in Progress)

These are initial thoughts, so nothing is final yet (some features may be released sooner if needed)

- [ ] **LSP Integration**: Explore adding support for Language Server Protocol (_currently in progress_).
- [ ] **Message Refactor**: Simplify how data messages are structured, aligning them with JSON-RPC conventions.
- [ ] **Transmission Protocols**: Add support for multiple ways to send data (TCP will still remain the default):
  - **File Path**: Allow users to specify a file path for local use, and let the server open and process the file directly.
- [ ] **WebSocket Support**: Bring back WebSocket support.
- [ ] **Debugging Tools**: Investigate integrating `debugpy`.
- [ ] **Hiero-Only Workflows**: Add support specifically for Hiero-only use cases.
  - At the moment it does work inside Nuke Studio which uses Hiero.
- [ ] **Maya Controller**: Same as Nuke and Houdini.
  - I know Maya already has some extensions that allow the user to send code, but if we are going to implement the LSP, we still need a dedicated controller.
- [ ] **PyPI Support**: Make it installable via PyPI for easier setup 
  - Might be impractical due to DCC's embedded Python environment.
- [ ] **API Integration**: Provide a simple API to interact with the server (likely requires pypi support). For example:

```python
import nukeserversocket as nss

with open("file.py") as f:
    script = f.read()

with nss.connect():
    nss.execute(script)
```
